name: Update WakaTime Stats

on:
  schedule:
    - cron: '0 * * * *'  # Runs the action every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Fetch WakaTime Stats and Update README
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        run: |
          echo "Fetching WakaTime stats..."
          curl -s "https://wakatime.com/badge/user/${{ secrets.WAKATIME_API_KEY }}.svg" -o wakatime-stats.svg
          echo '![WakaTime stats](./wakatime-stats.svg)' > README.md
          echo "WakaTime stats updated in README."

      - name: Commit changes
        run: |
          git config --global user.email "mohantyankit619@gmail.com"
          git config --global user.name "Ankitmohanty2"
          git add README.md wakatime-stats.svg
          git commit -m "Updated WakaTime stats"
          git push
